server:
  port: 8001
mybatis:
  type-aliases-package: com.edc.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.60.202:3306/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: longlong
