server:
  port: 4399
spring:
  application:
    name: springcloud-config-server-4399
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/edclol/springcloud-edc-config-server.git
